version: "3.8"
services:
  mysql:
    container_name: db_mysql
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
    - "33306:3306"
    volumes:
    - "./volumes/mysql:/var/lib/mysql"
